#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by script.
##
##############################################################################

APP_HOME=$(cd "${0%/*}" && pwd -P) || exit
APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

DEFAULT_JVM_OPTS ="-Xmx64m -Xms64m"

GRADLE_WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -r "$GRADLE_WRAPPER_JAR" ]; then
  echo "Missing gradle-wrapper.jar. Run: bash ./fetch_wrapper.sh" >&2
  exit 1
fi

# Use java from PATH
exec java $DEFAULT_JVM_OPTS -jar "$GRADLE_WRAPPER_JAR" "$@"
